version: 2
updates:
  - package-ecosystem: npm
    directory: "/src/csr"
    schedule:
      interval: daily
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled

  - package-ecosystem: terraform
    directory: "/deploy/azure/app/csr"
    schedule:
      interval: daily
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
